USE [master]
GO
/****** Object:  Database [APIDatabase]    Script Date: 2/13/2023 10:32:43 PM ******/
CREATE DATABASE [APIDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'APIDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\APIDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'APIDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\APIDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [APIDatabase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [APIDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [APIDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [APIDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [APIDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [APIDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [APIDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [APIDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [APIDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [APIDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [APIDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [APIDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [APIDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [APIDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [APIDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [APIDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [APIDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [APIDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [APIDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [APIDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [APIDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [APIDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [APIDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [APIDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [APIDatabase] SET RECOVERY FULL 
GO
ALTER DATABASE [APIDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [APIDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [APIDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [APIDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [APIDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [APIDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [APIDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'APIDatabase', N'ON'
GO
ALTER DATABASE [APIDatabase] SET QUERY_STORE = OFF
GO
USE [APIDatabase]
GO
/****** Object:  Table [dbo].[Invoice]    Script Date: 2/13/2023 10:32:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Invoice](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [date] NULL,
	[Description] [nvarchar](200) NULL,
	[TotalAmount] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Invoice] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InvoiceItem]    Script Date: 2/13/2023 10:32:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InvoiceItem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[InvoiceId] [int] NOT NULL,
	[Amount] [decimal](18, 2) NULL,
	[Quantity] [int] NULL,
	[UnitPrice] [decimal](18, 2) NULL,
	[LineAmount] [decimal](18, 2) NULL,
 CONSTRAINT [PK_InvoiceItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[InvoiceItem]  WITH CHECK ADD  CONSTRAINT [FK_InvoiceItem_InvoiceItem] FOREIGN KEY([InvoiceId])
REFERENCES [dbo].[Invoice] ([Id])
GO
ALTER TABLE [dbo].[InvoiceItem] CHECK CONSTRAINT [FK_InvoiceItem_InvoiceItem]
GO
USE [master]
GO
ALTER DATABASE [APIDatabase] SET  READ_WRITE 
GO
